---
title: "Biogas Ownership: Insights and Sustainability"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
    vertical_layout: scroll
    theme: yeti
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(highcharter)
library(gt)
library(htmltools)
library(viridis)
library(plotly)
library(knitr)
library(readr)
library(rtweet)
library(Rcpp)
library(textdata)
library(tidytext)
library(ggwordcloud)
library(tidyquant)
library(tm)
library(syuzhet)
library(wordcloud2)
library(qdapRegex)
library(DT)
```
```{r}
colors <- viridis::mako(n = 15)
```

Analysis
===============================


Row
---------------

###
```{r}
chart_sentiment 
```

###
```{r}
chart_sentiment_trends
```


Row
------------

###
```{r}
chart_mpw_organic
```

Row
---------------

###
```{r}
positive_words
```

###
```{r}
negative_words
```


Row
------------


###
```{r}
chart_emotion_score
```
Row
-------------

###
```{r}
chart_word_association
```

###
```{r}
chart_word_association1
```

###
```{r}
chart_word_association2
```

Row
-------------

###
```{r}
chart_word_association3
```

###
```{r}
chart_word_association4
```

###
```{r}
chart_word_association5
```

Row
-------------

###
```{r}
chart_word_association6
```

###
```{r}
chart_word_association7
```

###
```{r}
chart_word_association8
```

Row
------------

###
```{r}
polarity
```


Row
------------

###
```{r}
word_cloud
```
